name: Scheduled health check

on:
  schedule:
    - cron: "11 15 19 * *"

jobs:
  check_url:
    runs-on: ubuntu-20.04
    steps:
      - name: Health Check
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://fso-dex.onrender.com
          max-attempts: 3
          retry-delay: 5s
      - name: Discord success notification
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: success()
        with:
          severity: info
          details: Test Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Discord failure notification
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: failure()
        with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
